name: CI

on:
  push:
    branches: 
      - develop-actions2

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build PBO
      id: build
      run: |
        sudo add-apt-repository ppa:koffeinflummi/armake -y  || exit 0
        sudo apt-get update -y  || exit 0
        sudo apt-get install armake -y  || exit 0
        export VERSION=`cat description.ext  | grep -o 'onLoadName = ".*"' | grep -o 'v[0-9.][0-9.]*'`
        export FILENAME=7Cav_FullSpectrum_$VERSION.Altis.pbo
        echo ::set-output name=VERSION::$VERSION
        echo ::set-output name=FILENAME::$FILENAME
        armake build -w unquoted-string -w redefinition-wo-undef -w excessive-concatenation -x ".*" -x "*.pbo" -x "*.md" . 7Cav_FullSpectrum_$VERSION.Altis.pbo

    - name: Create Release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.build.outputs.VERSION }}
        release_name: Release ${{ steps.build.outputs.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ steps.build.outputs.FILENAME }}
        asset_name: ${{ steps.build.outputs.FILENAME }}
        asset_content_type: application/pbo
